Lecture 2
Letto228/Angular-learnjs-171022 pull request #18
Opened 2022-10-30 17:19 UTC by hitmaria

2022-11-02 04:13 UTC, Letto228 requested changes
Привет!
Отписался по тому, что заметил, посмотри и дай фидбек пожалуйста

2022-11-02 04:13 UTC, Letto228 commented on .eslintrc.json
> +				"@angular-eslint/no-empty-lifecycle-method": "off"
Почему отключила? Давай вернем, помогает пустые хуки не пропустить, которые код загрязняют

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +    <table style="width: 100%">
Хм, а почему через таблицу решила сделать? Есть же grid контейнеры, или через flex можно попробовать. Такой подход считается устаревшим и грузит шаблон не нужными тегами

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +    <table style="width: 100%">
И не очень нравится хардкод `style` в html. Это не тот случай, когда им стоит пользоваться, в целом хардкода `style` в html стоит избегать

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +              [matBadgeHidden]="shopBagBadgeVisibility" aria-hidden="false" aria-label="favorite" fontIcon ="shopping_cart"></mat-icon>
Это же не преттиер так перенес?)
Я предлагаю придерживаться такого форматирования:
```
<mat-icon
              matBadgeSize="small" 
              aria-hidden="false"
              aria-label="favorite"
              fontIcon ="shopping_cart"
              [matBadgeHidden]="shopBagBadgeVisibility"
              [matBadge]="productCount"
></mat-icon>
```
Как показывает практика это написание проще читается и воспринимается

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	constructor() {}
Давай пустые методы сносить. В частности пустые `constructor` и `ngOnInit`

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	readonly productTitle = productMock.name;
Сейчас можно оставить это в таком виде, но в будущем, когда карточка станет динамичной(значение сможет обновляться) - такой подход доставит больше хлопот, придется каждый раз переинициализировать данные свойства. По этому, если в шаблоне компонента просто нужны данные без какой либо логики - давай сразу через интерполяцию их и отображать, минуя лишние свойства в компоненте.

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	readonly productImageHeightPx = '300';
Это кажется вообще можно в файл стилей унести и через класс прописать высоту, нет необходимости хранить эти данные в классе компонента

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Давай уходить от практики с `else`, она расширяется и читается намного хуже чем практика с ранним return 
```
event.stopPropagation();

if (!this.initialFavotiteData.value) {
			this.initialFavotiteData.value = true;
			this.initialFavotiteData.icon = 'favorite';

      return;
}

this.initialFavotiteData.value = false;
this.initialFavotiteData.icon = 'favorite_outline';
```

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.productCount++;
Я бы посмотрел в сторону явного присваивания нового значения. Инкрементацию обычно используют еслу нужно возвращаемое значение, в нашем же случаи нужно просто увеличить счетчик на единицу
```
this.productCount += 1
```

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Тот же комментарий про if/else и ранний return + я бы вообще посмотрел в сторону тернарного оператора
А если еще глубже капнуть - зачем тут строка? Кажется обычным boolean можно обойтись: `this.shopBagBadgeVisibility = this.productCount === 0`
И рекомендую использовать тройное равенство(`===`), чтобы поддерживать строгую типизацию в коде и не сравнивать разношерстные типы

2022-11-02 04:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		return `${productMock.price} $`;
Это я бы тоже перенес в шаблон, логики как таковой нет, относится по большей части ко вью. Так зачем нам в таком случае хранить целый метод под такое

2022-11-02 19:04 UTC, hitmaria commented on .eslintrc.json
> +				"@angular-eslint/no-empty-lifecycle-method": "off"
Отключила потому, что на момент выполнения задания не дошли до onInit(), а он автоматически создался в компоненте. Не разобралась, можно ли его удалить. А ESlint ругался на него.  Согласна, сейчас можно вернуть.

2022-11-02 19:07 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.html
> +    <table style="width: 100%">
ага. попробую через grid. раньше не пользовалась им просто.
Согласна, что писать стили в html - моветон. Но бывает, что сбиваюсь на такое. Принято.

2022-11-02 19:22 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.html
> +              [matBadgeHidden]="shopBagBadgeVisibility" aria-hidden="false" aria-label="favorite" fontIcon ="shopping_cart"></mat-icon>
хм... да, действительно.. А prettier не отработал при коммите почему-то. Cейчас выполнила команду и действительно отформатировалось именно как ты написал.
Видимо это произошло потому, что в файле .lintstagedrc.json нет команды обработки преттиром для файлов html

2022-11-02 19:23 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	constructor() {}
Да, я уже поняла. У меня как раз из-за них ругался Eslint

2022-11-02 19:26 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	readonly productTitle = productMock.name;
Да, начала с простого. Потом поняла, что можно было обратиться напрямую, и так было бы лучше, но забыла, что хотела попробовать поменять.

2022-11-02 19:31 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	readonly productImageHeightPx = '300';
:) Sorry... На productImageHeightPx  вообще нет ссылок в html. Тоже забыла удалить.
Вообще не могу вспомнить с какой целью написала его тут. Возможно где-то в моем воображении хотела изменять это значение в зависимости от чего-то

2022-11-02 19:34 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Ок. Не знала, что это популярная практика. Мне казалось, что конструкция с else читается естественнее.

2022-11-02 19:38 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.productCount++;
К сожалению, я не поняла в чем разница. 
и будет ли плохо если запись будет в виде this.productCount = this.productCount+1

2022-11-02 19:49 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
хм... ну да true в качестве строки - это очень загадочно.  Наверное это не внимательность.
this.shopBagBadgeVisibility = this.productCount === 0 - да, тоже поняла, мне просто гораздо легче воспринимать конструкцию if/else. Она громоздкая, но мне кажется гораздо более очевидной.
Есть правда вопрос по поводу атрибута shopBagBadgeVisibility. У меня как-то не укладывается в голове, почему 
свойство подразумевающее "Видимость" нужно установить в true, чтобы сделать НЕ видимым?

2022-11-02 19:50 UTC, hitmaria commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		return `${productMock.price} $`;
Согласна.

2022-11-02 19:53 UTC, hitmaria commented
Мне исправлять? Просто сразу не делаю, так как есть сомнения, обсуждение замечаний, же не собьется, если я переделаю исходный код?

2022-11-06 16:11 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +              [matBadgeHidden]="shopBagBadgeVisibility" aria-hidden="false" aria-label="favorite" fontIcon ="shopping_cart"></mat-icon>
Да, при добавке плагина, не подогнал .lintstagedrc.json, к след занятию устраню данный недочет

2022-11-06 16:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	readonly productImageHeightPx = '300';
И такое бывает🙃

2022-11-06 16:18 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Мне наоборот практика  c `else` кажется чужестранной) возможно дело привычки. Но я пробовал и такую и такую практику, с ранним конструкции с ранним ретерном выглядят более читаемо и плоско, имхо с ними даже проще функции на отдельные блоки(подфункции) разделять.

2022-11-06 16:31 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.productCount++;
`this.productCount += 1` and `this.productCount = this.productCount+1` - две равносильные записи с явным присваиванием нового значения(явно указывается `=`), но первая запись короче в написании и не имеет дублирующего обращения к `this.productCount`.
Почему считаю инкриментацию не подходящей, потому что нет явного присваивания, то есть знак `=` отсутсвует, считается, что перезаписывание значения становится менее явным. Но это холиварная тема, есть и сторонники инкриментации `this.productCount++`, но встречая такую запись я воспринимаю ее всегда так: мы инкриментируем переменную и возращаем ее значение в другую переменную, так, а почему возвращаемое значение никуда не передается ..., а, то есть просто инкриментируем переменную

2022-11-06 16:32 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.productCount++;
В целом, такого подхода не я один придерживаюсь, в частности, в у меня в команде стоит такая же установка - используем явное присваивание

2022-11-06 17:14 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Мне наоборот казалось, что тернарник в таких случаях более очевиден и компактней чем конструкция if/else. Я всегда когда вижу тернарник, подразумеваю, что инициализация переменой происходит по какому либо условию, а блок if/else может использоваться для всего, по этому инициализация в нем мне кажется менее очевидной.
Но, конечно, тернарник должен быть не громоздким, если условие большое - стоит вынести его в говорящую константу, так тернарник станет более читаемым, еще вычисляемое значение можно получать из функции или метода, если оно сложно высчитывается, так тернарник тоже станет проще восприниматься

2022-11-06 17:17 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		} else {
Ну а в данном случаи вообще флаг для тернарника | блока if/else является значением которое должно попасть в переменную, по этому очень странно его значение было бы не присваивать)

2022-11-06 17:18 UTC, Letto228 commented
Привет!
Отписался по комментариям, если будут вопросы, давай в дискорде дообсуждаем, в целом все супер, МР закрываю

2022-11-06 17:18 UTC, closed without merging