feat: add product-card.component
Letto228/Angular-learnjs-171022 pull request #21
Opened 2022-11-01 08:00 UTC by navoznova

2022-11-02 03:48 UTC, Letto228 requested changes
Утро доброе
Оставил пару комментов, посмотри пожалуйста

2022-11-02 03:48 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +            (click)="buyProduct($event, product._id)"
В данном случаи из класса компонента можно получить доступ к продукту - `this.product._id`. По этому я бы предложил не загружать функцию аргументами и передать в нее только `$event`, а `product._id` получить в самом методе из класса компонента

2022-11-02 03:48 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +            color="primary">Buy</button>
Я предлагаю придерживаться такого форматирования
```
<button
            (click)="buyProduct($event, product._id)"
            mat-raised-button 
            color="primary"
>
            Buy
</button>
```
Как показывает практика - оно проще читается и воспринимается

2022-11-02 03:48 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	ngOnInit(): void {}
Давай пустые методы сносить. В частности пустые `constructor` и `ngOnInit`

2022-11-02 03:48 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	public selectedProductId: string = '';
Мало вероятно, что корзина у нас будет состоять исключительно из 1 продукта, но пусть будет пока так

2022-11-02 04:42 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.html
> +            (click)="buyProduct($event, product._id)"
поняла, fix

2022-11-02 04:43 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.html
> +            color="primary">Buy</button>
поняла, fix

2022-11-02 04:51 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	ngOnInit(): void {}
принято, fix

2022-11-02 06:55 UTC, Letto228 commented on .eslintrc.json
> +				"@angular-eslint/no-empty-lifecycle-method": "off"
И вот это давай вернем, у нас не должно быть пустых хуков, если они есть, значит что то мы пропустили

2022-11-02 06:55 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +            color="primary">
Осталось еще перенести `>`
```
        color="primary"
>
```

2022-11-02 06:55 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	public selectedProductId: string = '';
Свойство нам не нужно, можно удалить

2022-11-02 08:19 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	public selectedProductId: string = '';
принято

2022-11-02 08:21 UTC, navoznova commented on .eslintrc.json
> +				"@angular-eslint/no-empty-lifecycle-method": "off"
принято

2022-11-02 08:22 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.html
> +            color="primary">
принято

2022-11-06 17:25 UTC, Letto228 commented
Привет!
Все гуд! Апрув и закрываю МР

2022-11-06 17:25 UTC, closed without merging