feat: add input and output
Letto228/Angular-learnjs-171022 pull request #22
Opened 2022-11-02 07:16 UTC by navoznova

2022-11-06 17:42 UTC, Letto228 requested changes
Привет!
Пару комментариев накинул, не значительных по типизации, посомтри пожалуйста. В остальном все супер, поправим и можно закрывать МР

2022-11-06 17:42 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	getImageUrl() {
Просто подкину на будущее, что это похоже не гетер свойство идеологически, я бы его и использовал:
```
get getImageUrl(): string {
```

Давай добавим везде строгую типизацию возвращаемого значения

2022-11-06 17:42 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() productLike = new EventEmitter<IProduct['rating']>();
Кажется тут в типизации недочет, у нас же может и `undefined` уйти в событии судя по методу

2022-11-08 04:08 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() productLike = new EventEmitter<IProduct['rating']>();
поняла, спасибо

2022-11-08 04:18 UTC, navoznova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	getImageUrl() {
поняла, fix

2022-11-08 06:19 UTC, Letto228 approved these changes
Все супер, закрываю МР

2022-11-08 06:19 UTC, closed without merging