feat: lecture-2 dz (add product card)
Letto228/Angular-learnjs-171022 pull request #23
Opened 2022-11-02 19:03 UTC by tkarinka

2022-11-06 17:54 UTC, Letto228 requested changes
Привет!
Возникло пару вопросов, давай попробуем разобраться

2022-11-06 17:54 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +        Планшет Dexp Ursus S670 MIX станет незаменимым аппаратом для тех, кто не может жить без Интернета. Модель с SIM-картой и поддержкой модуля 3G обеспечивает свободный доступ к сети, где бы вы н
Я так понял, что ты написала этот блок, т.к. его нет в модели продукта, в целом если есть необходимость, нужно разговаривать с бэкенд разработчиками и технологами, нужно ли это поле и как его(в каком виде) добавить. Если все это для тебя очевидно, то то что я ниже описал, можно смело пропустить), если нет, то лучше прочитать, почему данное использование не катируется

Смотри, выше мы используем завязку на свойстве объекта, соответсвенно при смене значений, шаблон обновился бы автоматически, а тут ты прописываешь текст прямо в шаблоне, соответсвенно данный компонент для других продуктов не подходит.
Это я к тому, что давай уберем данный хардкод из шаблона и будем завязываться исключительно на данных модели которую использует компонент - `product`

2022-11-06 17:54 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +      <button mat-icon-button (click)="onAddShoppingCart; $event.stopPropagation()">
Не совсем я осознал, ты отлавливаешь клик по карточке выше у элемента `mat-card`, тут же ты функцию не вызываешь, но событие останавливаешь. К тому же событие ты останавливаешь как в шаблоне так и в методе. У меня вопрос, при ручном тесте все отрабатывает как ты и планировала?
Давай попробуем в этом моменте порядок навести

2022-11-06 17:54 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +  constructor() { }
Давай пустой конструктор и `ngOnInit` метод удалять, они только мешают и загрязняют компонент, как только они нам понадобятся - сразу добавим, труда нам это не составит

2022-11-08 10:18 UTC, tkarinka commented on src/app/modules/products-list/product-card/product-card.component.html
> +        Планшет Dexp Ursus S670 MIX станет незаменимым аппаратом для тех, кто не может жить без Интернета. Модель с SIM-картой и поддержкой модуля 3G обеспечивает свободный доступ к сети, где бы вы н
Я написала этот блок, так как у меня опыта совсем нет в Angular/ts/js, хотела просто "потыкать", посмотреть как это вообще работает)) Но я понимаю, что правильно использовать данные модели. Убрала этот кусок.

2022-11-08 10:18 UTC, tkarinka commented on src/app/modules/products-list/product-card/product-card.component.ts
> +  constructor() { }
убрала пустой конструктор и ngOnInit.

2022-11-08 10:31 UTC, tkarinka commented on src/app/modules/products-list/product-card/product-card.component.html
> +      <button mat-icon-button (click)="onAddShoppingCart; $event.stopPropagation()">
Видимо, я задачу изначально неправильно поняла. Думала надо сделать так, чтобы на клике в любом месте  карточки продукта отрабатывало событие (в консоле появился текст из onAddShoppingCart), кроме кнопочки buy.  Поэтому на mat-card-е я отлавливаю, а на кнопке останавливаю.  При ручном тесте так и работало. 
Посмотрела реализацию в ветке decision, переделала как там, теперь намного лучше смотрится)))

2022-11-08 10:32 UTC, tkarinka commented
Исправила.

2022-11-09 06:37 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +      <button mat-icon-button (click)="onAddShoppingCart; $event.stopPropagation()">
Супер!
Сделаю тогда себе пометку по ДЗ, что стоит наверное описание пересмотреть, спасибо)

2022-11-09 06:39 UTC, Letto228 approved these changes
Гуд, даю апрув и закрываю МР

2022-11-09 06:39 UTC, closed without merging