Lecture 5 decision
Letto228/Angular-learnjs-171022 pull request #29
Opened 2022-11-10 10:56 UTC by RomanShitovGH

2022-11-13 13:31 UTC, Letto228 requested changes
Привет!
Набросал комментариев по логике, посмотри пожалуйста

2022-11-13 13:31 UTC, Letto228 commented on src/app/modules/products-list/products-list.component.ts
>  	product: IProduct | undefined = undefined;
Эта переменная нам больше не нужна, можем ее выпилить

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/grouping-items-by-elements-size.ts
> +export function groupingItemsByElementsSize<T>(items: T[], elementsSize: number): Array<T[]> {
Можно убрать, вроде не используется нигде

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    while (items.length) {
Стоит вынести в отдельный метод, который будет создавать массив, собирать его и возвращать. То есть получим функцию для генерации нового массива с подмассивами, а уже в сетере будем выполнять явное присваивание

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +  @Input() set appPagination(items: T[] | undefined) {
А если у тебя изменится значение приходящее в инпут, то вставленный шаблон так и останется на странице, не обновится? Т.е. сброс `curentIndex$` не происходит, поток не пересчитывается, соответсвенно новый шаблон с обновленным контекстом на страницу не вставляется, кажется не совсем валидное поведение, давай немного доработаем

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    while (items.length) {
Тут еще момент, если обновится инпут, то заново будем пересчитывать массив, но он нигде не зануляется, не сбрасывается. Соответсвенно в массиве будет предыдущие значения + новые значения. Надо бы добавить сброс значения

P.S. если пойти по способу, что я описал в основном комменте, то сброс будет не нужен, т.к. отдельный метод(или, даже, чистая функция) будет собирать новый массив и возвращать его, и этот возвращаемый массив мы присвоим свойству `mas`

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +  private mas: T[][] = [];
Давай дадим более говорящие нейминги

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +			back: this.back.bind(this),
Предлагаю ввести стандарт по тому, как в контекст будем передавать методы и применить его и для одного и для другого метода. Я бы остановился на стрелочных функциях

2022-11-13 13:31 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +      this.mas.push(items.splice(0, this.elem));
Касаемо `splice`: он влияет на сам масив к которому применяется метод. В аргументе приходит ссылка на исходный массив, а не копия массива(нас колько я помню JS), соответсвенно, исходный массив у тебя станет пустым и кажется это не есть хорошо. Столкнулись как раз с проблемами мутаций. В общем тут тоже несколько вариантов: 1 - сделать копию массива при его получении и работать с ним; 2 - сделать через `reduce` метод, по примеру как у меня; В общем надо избавиться от мутаций исходного массива

2022-11-14 05:23 UTC, RomanShitovGH commented on src/app/modules/products-list/products-list.component.ts
>  	product: IProduct | undefined = undefined;
готово

2022-11-14 05:26 UTC, RomanShitovGH commented on src/app/shared/pagination/grouping-items-by-elements-size.ts
> +export function groupingItemsByElementsSize<T>(items: T[], elementsSize: number): Array<T[]> {
у меня в проекте такого и нет...
я не нашел

2022-11-14 18:14 UTC, closed without merging