Lecture 5 decision
Letto228/Angular-learnjs-171022 pull request #30
Opened 2022-11-13 16:34 UTC by Eduardossssss

2022-11-14 16:33 UTC, Letto228 requested changes
Привет!
Все круто, молодец! Накинул пару комментариев для доработки, посмотри пожалуйста

2022-11-14 16:33 UTC, Letto228 commented on src/app/modules/products-list/products-list.component.html
> +  <ng-template #productTemplate let-product>
Я бы шаблон вынес из тегов `app-paginator`, чтобы не складывалось ложного впечатления, что его положение как то влияет на вставку. Если он будет снаружи, даже восприниматься должно проще - как некий абстрактный шаблон с которым будет происходит работа в компоненте, т.к. он передан в его инпут параметр

2022-11-14 16:33 UTC, Letto228 commented on src/app/shared/carousel/carousel.directive.ts
> +	private groupingItemsByElementsSize<T>(items: T[], elementsSize: number): Array<T[]> {
Я бы вынес в отдельную функцию, т.к. это чистая функция не завязанная на классе

2022-11-14 16:33 UTC, Letto228 commented on src/app/shared/carousel/carousel.directive.ts
> +	private groupingItemsByElementsSize<T>(items: T[], elementsSize: number): Array<T[]> {
Она усложняет чтение логики класса

2022-11-14 16:33 UTC, Letto228 commented on src/app/shared/paginator/paginator.component.html
> +      <div class="paginator__number" (click)="selectIndex(index)">{{ index + 1 }}</div>
Мне казалось ты хотел с динамическим elementSize сделать, почему убрал, какие сложности возникли?

2022-11-14 16:33 UTC, Letto228 commented on src/app/shared/paginator/paginator.component.html
> +        ngFor
Есть безумная мысль, если будешь делать доработки, давай и это пропишем через сахарный синтаксис?)

2022-11-14 16:33 UTC, Letto228 commented on src/app/shared/paginator/paginator.component.ts
> +  constructor() { }
И давай уберем пустые методы

2022-11-18 14:18 UTC, Eduardossssss commented on src/app/shared/paginator/paginator.component.html
> +      <div class="paginator__number" (click)="selectIndex(index)">{{ index + 1 }}</div>
когда прокидывал значение в директиву, то оно прокидывалось только один раз в самом начале. Когда через дропдаун выбирал другое значение elementSize, то больше оно не прокидывалось

2022-11-18 14:56 UTC, Eduardossssss commented on src/app/shared/paginator/paginator.component.html
> +        ngFor
`<ng-container
        *ngFor="let product of pageProducts"
        [ngTemplateOutlet]="productTemplate"
        [ngTemplateOutletContext]="{ product: product }">
</ng-container>`

2022-11-18 14:56 UTC, Eduardossssss commented on src/app/shared/paginator/paginator.component.html
> +        ngFor
Вот так получается через сахарный синтаксис?

2022-11-19 15:58 UTC, Eduardossssss commented
Привет! Залил также атрибутивную директиву в эту же ветку.

2022-11-21 05:24 UTC, Letto228 commented on src/app/shared/paginator/paginator.component.html
> +        ngFor
Не совсем, ты его частично использовал. Все инпуты по хорошему тоже надо занести в `*ngFor="..."`. Для этого тебе нужно внутрь `*ngFor="..."` поместить название инпута без префикса `ngFor`, c трансформацией `[ngForOf]="pageProducts"` -> `*ngFor="... of pageProducts"` у тебя все получилось, осталось `[ngForTemplate]` по похожему принципу перевести. Не забывай, что есть вспомогательные символы для разделения и улучшения семантики: `:`(Как пример - `of: pageProducts`) - для указания инпута и переданного в него параметра, `;`(Как пример - `let product; of: pageProducts`) - для разделения параметров и инпутов в сахарном синтаксисе. 

P.S. `let product of pageProducts` - устоявшеяся конструкция, ее можно так и оставить, просто добавь после нее `;` и предавай аргументы дальше(`let product of pageProducts; ...`)

P.S.S ngTemplateOutlet - это другая структурная директива, нам она тут излишне) + 2 структурные директивы нельзя к 1 элементу применять, была бы ошибка по идее

2022-11-21 05:33 UTC, Letto228 commented on src/app/shared/paginator/paginator.component.html
> +      <div class="paginator__number" (click)="selectIndex(index)">{{ index + 1 }}</div>
Я в коммитах посмотрел - увидел, что ты использовал:
```html
 <mat-form-field appearance="fill">
        <mat-select [(value)]="selectedPageSize">
          <mat-option [value]="option" *ngFor="let option of pageSizeArray">{{ option }}</mat-option>
        </mat-select>
</mat-form-field>
```

`[(value)]="selectedPageSize"` - применение шаблонных форм, в результате у тебя просто обновлялось значение в `selectedPageSize`. Но `selectedPageSize` больше никуда не передавалось, а должно было в инпут `elementsSize`(`elementsSize: selectedPageSize`). Думаю за счет этого значения не обновлялись.

Сегодня будем изучать шаблонные формы в том числе, после них предлагаю вернуться и попробовать сделать еще раз, динамическое изменение размера отображаемых элементов

2022-11-21 05:42 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев + оставил ответы на твои сообщения, посмотри пожалуйста

2022-11-21 05:42 UTC, Letto228 commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +    if(borderTopOffset < 100) {
`100` в таком случаи называют магическим числом) Давай вынесем в константу с говорящим названием?

2022-11-21 05:42 UTC, Letto228 commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +      this.loadData.emit('top');
`top` и типизация по string(`new EventEmitter<string>();`) тут тоже не очень хорошо подходит. Я бы посмотрел в сторону создания `enum` с возможными направлениями загрузки(`enum LoadDirection {...}`) и типизировал бы output через enum(`new EventEmitter<LoadDirection>();`)

2022-11-21 05:42 UTC, Letto228 commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +      this.loadData.emit('top');
Таким образом получим более строготипизированое API

2022-11-21 05:42 UTC, Letto228 commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +      this.loadData.emit('top');
Еще мне показалось, что тут не хватает return, мы же скролить можем только в одном направлении

2022-11-27 14:11 UTC, Eduardossssss commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +    if(borderTopOffset < 100) {
сделал

2022-11-27 14:11 UTC, Eduardossssss commented on src/app/shared/infinite-scrolling/infinite-scrolling.directive.ts
> +      this.loadData.emit('top');
сделал

2022-11-27 14:15 UTC, Eduardossssss commented on src/app/shared/paginator/paginator.component.html
> +        ngFor
я ngForTemplate перевел в template = productTemplate. Получилось *ngFor="let product of pageProducts; template = productTemplate". Дальше не знаю, что делать, появилась ошибка "'name' is unknow property ...". Я так понял, что он не видит контекст, но не знаю, как это исправить.

2022-12-04 17:18 UTC, Letto228 approved these changes
Привет, прошу прощения за длительную проверку
Просмотрел еще раз МР, все супер! Апруваю и закрываю

2022-12-04 17:18 UTC, closed without merging