feat: add filter pipe
Letto228/Angular-learnjs-171022 pull request #36
Opened 2022-11-20 08:30 UTC by Eduardossssss

2022-11-21 05:03 UTC, Letto228 requested changes
Привет!
Почти все гуд, но смутил 1 момент в интуитивности пайпа, посмотри пожалуйста

2022-11-21 05:03 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +        .some(
Интересный подход) Но смущает тот момент, что поиск происходит не интуитивно для пользователя.

Допустим, ты набираешь цифру 5, т.к. в названии искомого продукта есть такая цифра, а тебе выпадают все продукты, у которых в свойствах хоть раз упоминается 5: `feedbackCount: 5` - подойдет, `raiting: 5` - тоже подойдет, и т.д.

Давай фиксировать все таки поиск по конкретному свойству. Так сможем выстроить более интуитивный и понятный интерфейс для юзера

2022-11-21 05:38 UTC, Eduardossssss commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +        .some(
Добавил в пайп параметр для поля фильтрации.

2022-11-23 06:38 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +        .some(
Да, стало получше! Накину немного хороших практик:
1. Наверное согласишься, что `value[1]` и `value[0]` мало информации в себе несут о том, что хранится в этих значениях, т.е. мы приходим к тому, что код через какое то время будет сложно прочитать из-за неинформативности нейминга `value` и содержания его массива.

```ts
value => value[1] && (value[0] === filterField) && (String(value[1]).includes(lowerCaseValue))
```

По этому предлагаю воспользоваться деструктуризацией аргумента в таких случаях. По На нашем примере предложил бы что то вроде этого
```ts
([key, value]) => value[1] && (value[0] === filterField) && (String(value[1]).includes(lowerCaseValue))
```

2022-11-23 06:42 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +        .some(
2. Кажется и вовсе не нужно перебирать элементы?

element - объект, соответсвенно мы можем достать по ключу значение и просто сравнить его с тем, что получили в фильтре. Таким образом сложность поиска устремится к 0

```ts
.filter(
    element => element[filterField] && String(element[filterField]).includes(lowerCaseValue)
)
```

2022-11-24 12:34 UTC, Letto228 requested changes
Привет!
Оставил комментарий под прошлым комментарием) https://github.com/Letto228/Angular-learnjs-171022/pull/36#discussion_r1030075839

2022-11-26 13:50 UTC, Eduardossssss commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +        .some(
Сделал код чище и понятнее.

2022-12-04 17:13 UTC, Letto228 reviewed
Привет!
Все гуд, апруваю и закрываю МР

2022-12-04 17:13 UTC, closed without merging